name: Lint Commit Messages

on:
  pull_request:

jobs:
  commitlint:
    name: Commitlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5.0.1
