name: Draw.io Compiler

on:
  pull_request:
    types:
      - opened
      - synchronize
      - closed
    paths:
      - '**/*.drawio'

env:
  DISPLAY: :99.0
  DRAWIO_VERSION: 14.6.13
  DRAWIO_DISABLE_UPDATE: true

jobs:
  drawio:
    name: Draw.io Compiler
    runs-on: ubuntu-latest
    steps:
      - name: Instaling drawio
        timeout-minutes: 3
        run: |
          sudo apt-get install libappindicator3-1
          wget https://github.com/jgraph/drawio-desktop/releases/download/v${{ env.DRAWIO_VERSION }}/drawio-amd64-${{ env.DRAWIO_VERSION }}.deb
          sudo dpkg -i drawio-amd64-${{ env.DRAWIO_VERSION }}.deb
          sudo rm drawio-amd64-${{ env.DRAWIO_VERSION }}.deb
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          drawio --help
      - name: Checkout
        uses: actions/checkout@v2.3.5
        with:
          fetch-depth: 2
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Check updated files
        id: getfile
        run: |
          echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r ${{ github.event.pull_request.head.sha }} | grep -e '.*\.drawio' | xargs)"
      - name: Updated drawio files
        run: |
          echo ${{ steps.getfile.outputs.files }}
      - name: Compiling files
        timeout-minutes: 15
        run: |
          for f in ${{ steps.getfile.outputs.files }}; do drawio -r -x -f png $f; done
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          committer: GitHub <noreply@github.com>
          base: ${{ github.event.pull_request.head.ref }}
          commit-message: 'docs: updating drawio based images'
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          delete-branch: true
          branch: auto-generated-for-PR-${{ github.event.pull_request.head.ref }}-${{ github.event.pull_request.number }}
          title: '[bot] PR for #${{ github.event.pull_request.number }}'
          body: 'Please merge this PR to #${{ github.event.pull_request.number }}'
      - name: Comment to PR
        if: steps.cpr.outputs.pull-request-number
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: 'Please merge #${{ steps.cpr.outputs.pull-request-number }} before merging this PR'
