name: Node.js

on:
  push:

jobs:
  check:
    name: Node.js check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Node.js steps
        uses: ./.github/actions/node
