name: Node.js

on:
  push:

jobs:
  check:
    name: Node.js check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Node.js steps
        uses: ./.github/actions/node
